# Generated by Django 4.2 on 2026-09-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
